### ISSUE TITLE
Выбрать архитектуру-фреймворк для проекта

### ISSUE THREAD

**Issue by alexbaumgertner** [freecodecamp-spb/web-dev-cources#1]
Выбрать фреймворк или обойтись просто чистым HTML/CSS/javascript.

Можно сделать так — пока в папке `html-prototype` сделать просто статичную верстку. Причем, опытные разработчики только помогают и объясняют — верстают те, кто хочет научиться :).

@freecodecamp-spb/developers

**Comment by alexbykoff** [comment]
ну да, нечто подобное я в слэке и предложил.
Делать как будто по урокам, начиная с верстки и проч. Только народ нужно затянуть в гитхаб, но так, чтобы никто не сошел с ума =)

на FCC, помнится, глава была вроде по гиту
