### ISSUE TITLE
Спрятать ключи от Mlab и auth0

### ISSUE THREAD

**Issue by alexbaumgertner** [freecodecamp-spb/web-dev-cources#101]
Надо придумать, как безопасно прятать ключи, реализовать это и перегенерировать ключи для mlab и auth0

**Comment by alexbaumgertner** [comment]
![web-dev-courses settings heroku 2016-12-12 12-11-40](https://cloud.githubusercontent.com/assets/223620/21093672/30112a50-c064-11e6-89b9-ff50fe0295c0.png)

**Comment by ierhyna** [comment]
В приложении для регистрации в нашем слаке сделано через Config variables, они вызываются в Procfile: `web: bin/slackin --port $PORT $SLACK_SUBDOMAIN $SLACK_API_TOKEN`, а потом используются через `args`:
```
var org = args.sub[0] || process.env.SLACK_SUBDOMAIN
var token = args.sub[1] || process.env.SLACK_API_TOKEN
```

**Comment by ierhyna** [comment]
Попробую сделать

**Comment by alexbaumgertner** [comment]
https://12factor.net/ru/config

**Comment by ierhyna** [comment]
Если хранить ключи в Config variables, то нужно сделать, чтобы эти ключи были доступны локально у всех разработчиков, и очень желательно, оффлайн.

Heroku предлагает вариант с использованием [heroku local](https://devcenter.heroku.com/articles/heroku-local). Но это не будет работать, если нет интернета, и требует установки heroku tools. На мой взгляд, это осложнит процесс разработки.

Наиболее простым решением лично мне кажется использовать локальные переменные через экспорт в .bash_profile, но не понятно, как безопасно можно передавать их между разработчиками.

Поэтому вопрос, как это лучше сделать?

**Comment by alexbaumgertner** [comment]
1) Можно хранить в гугл-докс и расшарить документ между разработчиками - devOps
2) Можно в slack в прикрепленной теме в канале проекту.

Плюс можно написать небольшую инструкцию, как каждый желающий может сгеренировать свои ключи в mlab и auth0, чтобы для разработки не использовать продакшен доступы.

**Comment by alexbaumgertner** [comment]
Я бы наверное просто отправил бы продакшен ключи всем разработчикам с правами выкладки приложения, а для разработки использовал бы персональные разработчичиские БД и авторизацию.

Вопрос только что продакшен ключи надо сделать от имени организации + для БД настроить бекап.

**Comment by alexbaumgertner** [comment]
Сделано в https://github.com/freecodecamp-spb/web_dev_courses_Front_End/pull/102
