### ISSUE TITLE
Опечатка в названии репозитория: cources --> courses

### ISSUE THREAD

**Issue by ghost** [freecodecamp-spb/web-dev-cources#23]
https://en.wikipedia.org/wiki/Course_%28education%29

**Comment by blackio** [comment]
@tomkallen Поправим наболевший вопрос? Он тут уже сколько висит, не дело)

**Comment by alexbykoff** [comment]
Угу

**Comment by alexbaumgertner** [comment]
Доделал исправление опечатки в https://github.com/freecodecamp-spb/web-dev-courses/pull/39
