### ISSUE TITLE
Составить техническое задание (ТЗ)

### ISSUE THREAD

**Issue by alexbaumgertner** [freecodecamp-spb/web-dev-cources#3]

**Comment by alexbaumgertner** [comment]
Предлагаю — список курсов с показом языка (русский/анл), длительности, стоимости.

По клику на пункт — открывается страница курса: подробная информация, отзывы, похожие и тд.
Курсы можно добавлять через форму  `/courses/new`

**Comment by alexbykoff** [comment]
Списки курсов в базе хранить? Если так, то нужно понять, где проект поднимать.

**Comment by alexbaumgertner** [comment]
Пока можно в json-файле. Для разработки есть API Mock (заглушка с тестовыми данными), например http://jsonplaceholder.typicode.com/

**Comment by alexbaumgertner** [comment]
Еще:
https://www.mockable.io/ (конфигурируется гибко)
https://jsonstub.com/
https://apiary.io/
https://getsandbox.com/

**Comment by alexbykoff** [comment]
Собственно я вижу это как одностраничное приложение на Angular, которое либо расписывает json'ы в виде списков, либо хранит все это в базе. Нагружать сайт страницами и фичами вообще нет смысла, для начала хотя б отработать вывод списков и добавление, а потом уже ковырять визуальщину, учитывая что все легко переносимо

**Comment by MaxBt** [comment]
В trello появилось ТЗ https://docs.google.com/document/d/1M636h7PoSqQjCt8aXKs0tqPe8M5vZ9x7Q5z2pUG_0XQ/edit?usp=sharing
Там и дискуссия. Issue наверно, можно закрыть.

**Comment by alexbaumgertner** [comment]
Добавь пожалуйста в issue ссылку на задачу в Трелло и можно закрывать.

**Comment by MaxBt** [comment]
https://trello.com/c/PvYR22Ee/21-- ТЗ в Трелло.
