### ISSUE TITLE
[feature/HTML+CSS]>main.css: .nav li границы

### ISSUE THREAD

**Issue by alexbykoff** [freecodecamp-spb/web-dev-cources#35]
- `.nav li` не имеет margin что приводит к [такому](http://image.prntscr.com/image/a9cadd38fc2c4a708cd9987d3aa64e51.png) результату 
- `.nav a:hover` выдает печальные результаты на диспелеях 4:3 < 1024px
- `@media screen and (min-width: 600px)``.nav li`разбит на 2 части

**Comment by alexbykoff** [comment]
iPad в горизонтальном — та же проблема (1024px)

**Comment by blackio** [comment]
fixed - .nav li не имеет margin что приводит к такому результату

**Comment by blackio** [comment]
fixed - @media screen and (min-width: 600px).nav liразбит на 2 части

**Comment by blackio** [comment]
fixed.
