### ISSUE TITLE
Del or Not? /html-prototype/courses.html

### ISSUE THREAD

**Issue by blackio** [freecodecamp-spb/web-dev-cources#37]
Нужна ли отдельная страница курсов или же удалим, если она лишняя?

**Comment by alexbykoff** [comment]
Расширенная(раскрытая) карточка требует своего html так что нужно оставлять. единственное что создать ее в одном `<div>` для компонента React. Продумать ее составляющие. Head, Header, Body и Footer соответственно не нужны.
Либо пересоздать заново, используя карточку из списка курсов.

**Comment by blackio** [comment]
@tomkallen теперь понял для чего она будет предназначаться, спасибо
