### ISSUE TITLE
Актуализировать ветку dev

### ISSUE THREAD

**Issue by alexbaumgertner** [freecodecamp-spb/web-dev-cources#40]
По результатам встречи 8 мая 2016

> Пост - напоминалка (+информирование тех, кто не был ) 
> Внимание, единственная актуальная на данный момент ветка: feature/backend

Нужно посмотреть, каких коммитов не хватает в dev.

**Comment by alexbykoff** [comment]
Сделано. Код протестирован @vikulov-roman

**Comment by alexbaumgertner** [comment]
@tomkallen нужно поправить описание в https://github.com/freecodecamp-spb/web-dev-courses?

Сейчас там так:

> Онлайн каталог курсов разработчиков (текущая ветка для разработки - /server)
