### ISSUE TITLE
Fix browser Sync

### ISSUE THREAD

**Issue by alexbaumgertner** [freecodecamp-spb/web-dev-cources#57]
Here https://github.com/freecodecamp-spb/web-dev-courses/blob/feature/meeting2205/gulpfile.js#L30-L32 

https://browsersync.io/docs/options/
https://github.com/floatdrop/gulp-batch
https://github.com/floatdrop/gulp-watch

**Comment by alexbykoff** [comment]
Коллбэки аутентификации бросают обратно на 3000 и браузерсинк умирает (см.`passport.js`)
Тут надо воркэраунд курить

**Comment by alexbykoff** [comment]
Работает
