### ISSUE TITLE
Remove Bootstrap

### ISSUE THREAD

**Issue by alexbaumgertner** [freecodecamp-spb/web-dev-cources#59]
Думаю, можно обойтись без Bootstrap
- лишняя большая библиотека
- ненаглядные наименования классов
  
  ``` css
    .col-md-3 {}
    .fa fa-search {}
    .col-lg-push-1 col-md-4 {}
  ```
  
  и тд.

Предлагаю (и готов внедрить) использовать методологию БЭМ https://ru.bem.info/methodology/

**Comment by alexbykoff** [comment]
- [x] Думаю, можно обойтись без Bootstrap. Удалено в `feature/meeting2205`
- [x] вычищены связи с БС
- [ ] ненаглядные наименования классов

> `fa-search` - это класс font-awesome

БЭМ внедрить  — дело хорошее, только если займешься, учти что если будешь использовать doubledash (--) Angular повалиться может

**Comment by alexbaumgertner** [comment]
Нет, `--` не буду, двойное подчеркивание классического стиля — наше все :) `__`

**Comment by alexbaumgertner** [comment]
NB:
удалено только в ветке `feature/meeting2205`

**Comment by alexbykoff** [comment]
Все правильно. Она не влита в дев. Ждали . Ну бэма и ещк от Ромы фиксов и соответственно она висит сейчас как первая в викли релизах. До субботы ее заполним и пушнем в дев за день до встречи.
