### ISSUE TITLE
Make weekly releases

### ISSUE THREAD

**Issue by alexbaumgertner** [freecodecamp-spb/web-dev-cources#60]
Давайте сделаем еженедельные релизы, например по воскресениям.
Будем заводить соответствующую ветку и объявлять ее текущей до контрольной точки.

Сейчас не очень понятно, какая ветка является актуальной (точно не `dev`), вроде `feature/meeting2205` но не уверен.

Например можно так: завести ветку `release/29_05_2016` и установить ее текущей до 29.05.2016.

/cc @freecodecamp-spb/developers @tomkallen

**Comment by blackio** [comment]
Хорошая идея, поддерживаю

**Comment by blackio** [comment]
На данный момент актуальна feature/meeting2205

**Comment by alexbykoff** [comment]
Поддерживаю. Но пересоберите ее на основе 2205. Я там все актуализировал кроме БЭМ

Бэм - Саша, по принципу устава =)

**Comment by alexbaumgertner** [comment]
@tomkallen Наше кредо — всегда  :)
https://www.youtube.com/watch?v=D_0FzNdFRzU

**Comment by alexbykoff** [comment]
Сделано
