### ISSUE TITLE
Collaborators disparity

### ISSUE THREAD

**Issue by alexbykoff** [freecodecamp-spb/web-dev-cources#63]
- Актуализировать и вычистить список людей, действительно работающих на WDC
- Закрыть прием людей на _именно этот_ проект для ускорения процесса

**Comment by MaxBt** [comment]
Не вижу смысла _закрывать приём_.
а) желающих не невесть сколько
б) если человек приходит и сможет влиться - что плохого?
в) народу на что-то ещё точно нет

Совершенно излишняя мера.

**Comment by alexbykoff** [comment]
Суть в том что уровень вхождения в проект уже довольно высок. Откатов назад уже себе не можем позволить.

**Comment by alexbykoff** [comment]
Сделано
