### ISSUE TITLE
Систематизация веток

### ISSUE THREAD

**Issue by blackio** [freecodecamp-spb/web-dev-cources#68]
Описать новые правила создания веток и правила работы с текущими ветками. (От недели к неделе)
Провести оптимизацию веток.

**Comment by alexbykoff** [comment]
В вики положите правило и именования

**Comment by alexbaumgertner** [comment]
Убрал лишние ветки https://github.com/freecodecamp-spb/web_dev_courses_Front_End/branches

**Comment by alexbaumgertner** [comment]
Осталась одна ветка https://github.com/freecodecamp-spb/web_dev_courses_Front_End/tree/feature/rost

Спросил у автора актуальность, жду ответа.

**Comment by alexbaumgertner** [comment]
Удалил все лишние ветки.
