### ISSUE TITLE
При загрузке страницы поиск приобретает класс ng-hide и не отображается

### ISSUE THREAD

**Issue by blackio** [freecodecamp-spb/web-dev-cources#69]
Страница выглядит следущим образом:
![screenshot from 2016-05-30 11 40 02](https://cloud.githubusercontent.com/assets/18497762/15644385/5b231558-265b-11e6-82ae-e8230e9f9780.png)
Класс:
![screenshot from](https://cloud.githubusercontent.com/assets/18497762/15644470/f6404d9e-265b-11e6-9bfb-c28e3c6aec10.png)
Если убрать класс, поиск появится, но работать не будет.

**Comment by blackio** [comment]
@tomkallen видимо ошибка при merge, проверил папку в чистом виде - все хорошо.

**Comment by alexbykoff** [comment]
Закрываю
