### ISSUE TITLE
Mobile landscape issue

### ISSUE THREAD

**Issue by alexbykoff** [freecodecamp-spb/web-dev-cources#70]
_iPhone 5:_
![iph5](https://cloud.githubusercontent.com/assets/5958213/15672507/b46dfd88-2739-11e6-9de2-fb2aa16f1ea1.PNG)

_iPhone 6:_
![iph6](https://cloud.githubusercontent.com/assets/5958213/15672524/cf153d40-2739-11e6-8dd3-3c3cf94b2914.PNG)

**Comment by blackio** [comment]
Предполагал нечто подобное, не проверил. Сделаю вечером

**Comment by blackio** [comment]
fixed for iphone5 and etc

**Comment by alexbaumgertner** [comment]
https://github.com/freecodecamp-spb/web-dev-courses/commit/e12d36ea79924b457df031cc6561d2b6334fa268

**Comment by alexbykoff** [comment]
Uneven headers (iPhone 5):

![default](https://cloud.githubusercontent.com/assets/5958213/15691685/df2ed4a8-2792-11e6-9ce6-725c7caec564.PNG)

**Comment by alexbykoff** [comment]
ac30267d
Сам починил
![default](https://cloud.githubusercontent.com/assets/5958213/15692076/14be7022-2795-11e6-8256-e59e3dd40714.PNG)
