### ISSUE TITLE
Card issue

### ISSUE THREAD

**Issue by alexbykoff** [freecodecamp-spb/web-dev-cources#73]
Full HD headers are dispalced while in fullhd form
need fixed `height`

**Comment by alexbaumgertner** [comment]
Is this issue actual?

**Comment by alexbykoff** [comment]
Если переходить на bootstrap или любую модульную систему то нет. Актуально для flex только

**Comment by alexbaumgertner** [comment]
Делаю компоненты на bootstrap.
Можно закрыть эту задачу?

**Comment by alexbaumgertner** [comment]
Задача устарела, при подобной баге на новой системе, заведем новую задачу.
