### ISSUE TITLE
Request overkill

### ISSUE THREAD

**Issue by alexbykoff** [freecodecamp-spb/web-dev-cources#81]
Обращаю внимание, что контроллер карточки уже держит дамп базы:
**card.controller.js:6** :    `$http.get('/courses/get')` в `$scope.courseList`
Тут либо к джейсону уже обращаться при поиске по тэгам, либо удалять в связи с новым алгоритмом поиска

P.S. `ng-repeat` временно выпилен?

**Comment by alexbaumgertner** [comment]
@tomkallen уточни пожалуйста актуальность этой задачи.

**Comment by alexbaumgertner** [comment]
Задача устарела.
